#:kivy 2.0.0
<janelaApp>:
    name: "janela"

    AnchorLayout:
        anchor_x: 'center'
        anchor_y: 'center'
        padding: 10
        spacing: 10
        Label:
            id: lblResposta
            text: "Bot: "
            font_size: 20
            size_hint: (0.8, 0.2)
            background_color: (0.2, 0.5, 0.8, 1)
            color: (1, 1, 1, 1)
            halign: 'left'
            valign: 'middle'
            border_color: (0.5, 0.5, 0.8, 1)
    
    AnchorLayout:
        anchor_x: 'left'
        anchor_y: 'bottom'
        padding: 0
        spacing: 0
        Label:
            id: lblUsuario
            text: "Usuario: "
            font_size: 20
            color: (1, 1, 1, 1)
            size_hint: (0.3, 0.2)

    AnchorLayout:
        anchor_x: 'center'
        anchor_y: 'bottom'
        padding: 5
        spacing: 10
        TextInput:
            id: txtPergunta
            name: 'pergunta'
            
            hint_text: "Digite aqui sua pergunta"
            font_size: 20
            multiline: True
            background_color: (0.2, 0.5, 0.8, 1)
            foreground_color: (1, 1, 1, 1)
            size_hint: (0.6, 0.2)
    
    AnchorLayout:
        anchor_x: 'right'
        anchor_y: 'bottom'
        padding: 5
        spacing: 10
        Button:
            id: btnEnviar
            name: 'botaoEnviar'
            text: "Enviar"
            font_size: 20
            color: (1, 1, 1, 1)
            background_color: (0.2, 0.5, 0.8, 1)
            size_hint: (0.2, 0.2)

<BackgroundColor@Widget>
    background_color: 1, 1, 1, 1
    canvas.before:
        Color:
            rgba: root.background_color
        Rectangle:
            size: self.size
            pos: self.pos
# Now you can simply Mix the `BackgroundColor` class with almost
# any other widget... to give it a background.
<BackgroundLabel@Label+BackgroundColor>
    background_color: 0, 0, 0, 0
    # Default the background color for this label
    # to r 0, g 0, b 0, a 0
# Use the BackgroundLabel any where in your kv code like below
BackgroundLabel
    text: 'Hello'
    background_color: 1, 0, 0, 1